### ISSUE TITLE
Relevancy post Meteor 1.0?

### ISSUE THREAD

**Issue by dandv** [zeroasterisk/MeteorRider#38]
Just wondering if this project is still useful now that Meteor includes Cordova/Phonegap support out of the box.

Only had a quick glance, but if the integration was superseded by official support, a deprecation notice would be useful.

**Comment by DanielOchoa** [comment]
I don't think it is relevant anymore. It was an interesting experiment for sure.

**Comment by zeroasterisk** [comment]
True - I had updated the linked blog posts with deprecation - and thought I had updated the README, but obviously not --- doing so now.
